/* Generated By:JavaCC: Do not edit this line. AnalizadorSintacticoTinyConstants.java */
package asint;

public interface AnalizadorSintacticoTinyConstants {

  int EOF = 0;
  int letra = 1;
  int digPos = 2;
  int digito = 3;
  int parteEntera = 4;
  int parteDecimal = 5;
  int parteExponcial = 6;
  int signo = 7;
  int subrayado = 8;
  int parApertura = 9;
  int parCierre = 10;
  int corApertura = 11;
  int corCierre = 12;
  int punto = 13;
  int puntoYComa = 14;
  int coma = 15;
  int dosPuntos = 16;
  int igual = 17;
  int suma = 18;
  int resta = 19;
  int mul = 20;
  int div = 21;
  int mod = 22;
  int and = 23;
  int or = 24;
  int not = 25;
  int mayor = 26;
  int menor = 27;
  int mayorIgual = 28;
  int menorIgual = 29;
  int distinto = 30;
  int igualdad = 31;
  int indireccion = 32;
  int intKW = 33;
  int real = 34;
  int bool = 35;
  int string = 36;
  int nullKW = 37;
  int trueKW = 38;
  int falseKW = 39;
  int proc = 40;
  int ifKW = 41;
  int then = 42;
  int elseKW = 43;
  int whileKW = 44;
  int doKW = 45;
  int seq = 46;
  int begin = 47;
  int end = 48;
  int record = 49;
  int array = 50;
  int of = 51;
  int newKW = 52;
  int delete = 53;
  int read = 54;
  int write = 55;
  int nl = 56;
  int var = 57;
  int type = 58;
  int cadena = 60;
  int id = 61;
  int enteros = 62;
  int reales = 63;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<letra>",
    "<digPos>",
    "<digito>",
    "<parteEntera>",
    "<parteDecimal>",
    "<parteExponcial>",
    "<signo>",
    "\"_\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\".\"",
    "\";\"",
    "\",\"",
    "\":\"",
    "\"=\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"and\"",
    "\"or\"",
    "\"not\"",
    "\">\"",
    "\"<\"",
    "\">=\"",
    "\"<=\"",
    "\"!=\"",
    "\"==\"",
    "\"^\"",
    "\"int\"",
    "\"real\"",
    "\"bool\"",
    "\"string\"",
    "\"null\"",
    "\"true\"",
    "\"false\"",
    "\"proc\"",
    "\"if\"",
    "\"then\"",
    "\"else\"",
    "\"while\"",
    "\"do\"",
    "\"seq\"",
    "\"begin\"",
    "\"end\"",
    "\"record\"",
    "\"array\"",
    "\"of\"",
    "\"new\"",
    "\"delete\"",
    "\"read\"",
    "\"write\"",
    "\"nl\"",
    "\"var\"",
    "\"type\"",
    "<token of kind 59>",
    "<cadena>",
    "<id>",
    "<enteros>",
    "<reales>",
  };

}
